version: "3"
services:
  postgres:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="auth-api","auth-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - supplier_api_data:/data/postgres
    ports:
      - 5438:5432 
volumes:
  supplier_api_data: {}  
